{
 "title": "_Microservice shop | OTUS",
 "description": "Otus homework5 dashboard ",
 "tags": [
  "otus",
  "microservice"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS & Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(method) (rate(http_server_requests_seconds_count{uri!~\"/actuator/prometheus|/health/\", status!~\"500|400|401\"}[5m]))",
       "legendFormat": "{{method}}-{{status}}-{{uri}}"
      }
     ]
    },
    {
     "title": "Kafka Requests Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(kafka_producer_topic_record_send_total[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency (by services)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "User quantiles 0.5, 0.95, 0.99",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{service=\"user\"}[5m])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{service=\"user\"}[5m])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{service=\"user\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Billing quantiles 0.5, 0.95, 0.99",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_requests_seconds_bucket{service=\"user\"}[5m])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{service=\"user\"}[5m])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_requests_seconds_bucket{service=\"user\"}[5m])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ERRORS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(http_server_requests_seconds_count{status=~\"500|400|401\", method=\"DELETE\"}[5m])",
       "legendFormat": "{{ERROR}}"
      },
      {
       "expr": "increase(http_server_requests_seconds_count{status=~\"500|400|401\", method=\"PUT\"}[5m])",
       "legendFormat": "{{ERROR}}"
      },
      {
       "expr": "increase(http_server_requests_seconds_count{status=~\"500|400|401\", method=\"GET\"}[5m])",
       "legendFormat": "{{ERROR}}"
      },
      {
       "expr": "increase(http_server_requests_seconds_count{status=~\"500|400|401\", method=\"POST\"}[5m])",
       "legendFormat": "{{ERROR}}"
      }
     ]
    },
    {
     "title": "Kafka ERRORS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(kafka_producer_topic_record_error_total[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true
  },
  {
   "title": "RPS & ERRORS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "ERRORS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 332 },
     "targets": [
      {
       "expr": "increase(user_delete_time_seconds_count{exception!=\"none\"}[5m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(user_find_time_seconds_count{exception!=\"none\"}[5m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(user_register_time_seconds_count{exception!=\"none\"}[5m])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(user_login_time_seconds_count{exception!=\"none\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Status and SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 2, "y": 276 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{application=\"$application\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Up Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 276 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Response time of 0.5, 0.95, 0.99 of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 279 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 279 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{method}}-{{status}}-{{uri}}"
      }
     ]
    },
    {
     "title": "ERRORS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{application=\"$application\", uri!=\"/actuator/prometheus\", outcome=\"SERVER_ERROR\"}[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Mean response time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 288 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{method}}-{{status}}-{{uri}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency (by method)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Register User quantiles 0.5, 0.95, 0.99, max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_requests_seconds_bucket{service=\"user\"}[5m])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_create_time_seconds{quantile=\"0.95\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_create_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      { "expr": "user_create_time_seconds_max", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Update User quantiles 0.5, 0.95, 0.99, max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "user_update_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_update_time_seconds{quantile=\"0.95\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_update_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      { "expr": "user_update_time_seconds_max", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Find User quantiles 0.5, 0.95, 0.99. max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "user_find_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_find_time_seconds{quantile=\"0.95\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_find_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      { "expr": "user_find_time_seconds_max", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Delete User quantiles 0.5, 0.95, 0.99, max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "user_delete_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_delete_time_seconds{quantile=\"0.95\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_delete_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      { "expr": "user_delete_time_seconds_max", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true
  }
 ]
}